spring:
  application:
    name: plataforma-reservas-medicas

  #configuración de la conexión a la base de datos
  #ahora mismo usa datos genéricos
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver

  #configuración de hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false

#configuración de seguridad, en un producto serio no dejar el secret a la vista, usar variables de entorno o un vault
security:
  jwt:
    secret: falseSecret
    expiration: 3600